name: afandim
description: A new Flutter application.

version: 3.8.52+30852

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2

  # Firebase Dep
  firebase_crashlytics: ^2.0.2
  firebase_core: ^1.1.0
  firebase_auth: ^1.1.2
  cloud_firestore: ^1.0.7
  firebase_storage: ^8.0.5
  firebase_messaging: ^9.1.3



  intl: ^0.17.0
  shared_preferences: ^2.0.5
  image_picker: ^0.7.4
  url_launcher: ^6.0.3
  flutter_launcher_icons: ^0.9.0
  timeago: ^3.0.2
  shimmer: ^1.1.2
  connectivity: ^3.0.3
  app_settings: ^4.1.0
  package_info: ^2.0.0
  device_info: ^2.0.0
  carousel_slider: ^3.0.0
  cached_network_image: ^2.2.0+1
  flutter_svg: ^0.20.0-nullsafety.3
  random_color: ^1.0.5
  google_maps_flutter: ^2.0.3
  flutter_html: ^1.3.0
  share: ^0.6.4+3
  html_unescape: ^1.0.1+3
  photo_view: ^0.9.0
  flutter_app_badger: ^1.1.2
  audioplayers: ^0.18.3
  get_it: ^4.0.2
  flutter_webview_plugin: ^0.3.11
  translator: ^0.1.4
  uni_links: ^0.4.0

  fluttertoast: ^8.0.6
  bubble: ^1.1.9+1
  flutter_countdown_timer: ^3.0.0
  get: ^4.1.1
  geocoding: ^2.0.0
  pin_code_fields: ^6.1.0
  google_fonts: ^2.0.0



  #  State management
  flutter_riverpod:

  dio: ^3.0.9
  dio_http_cache: ^0.2.11
  #  To Get All Country Codes
  country_code_picker: ^2.0.1
  sms_autofill: ^1.2.7

  # Animation
  flutter_villains: ^1.2.1
  lottie: ^1.0.1


#Get Location
#  location: ^4.1.1
  geolocator: ^7.0.3


dependency_overrides:
  flutter_plugin_android_lifecycle: ^1.0.2
  archive: ^3.0.0
  crypto: ^2.1.1+1
  http_parser: ^4.0.0
  intl: ^0.17.0-nullsafety.2


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  ios: true
  android: true
  image_path: "assets/icons/big_icon.png"

flutter:

  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/map_styles/
    - assets/sounds/
    - locale/

  fonts:
    - family: Tajawal
      fonts:
        - asset: assets/fonts/Tajawal-Regular.ttf
          weight: 400
          style: normal
        - asset: assets/fonts/Tajawal-Bold.ttf
          weight: 700
          style: normal

    - family: GoogleSans
      fonts:
        - asset: assets/fonts/GoogleSans-Regular.ttf
          weight: 400
          style: normal
        - asset: assets/fonts/GoogleSans-Bold.ttf
          weight: 700
          style: normal

    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
          weight: 400
          style: normal
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700
          style: normal

    - family: MyriadPro
      fonts:
        - asset: assets/fonts/MyriadPro.otf
          weight: 400
          style: normal
        - asset: assets/fonts/MyriadPro-Bold.otf
          weight: 700
          style: normal

